"""add object id to channel catalogue

Revision ID: e4aa4444977d
Revises: b8f3e33c10fb
Create Date: 2026-09-18 01:14:22.950806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4aa4444977d'
down_revision: Union[str, Sequence[str], None] = 'b8f3e33c10fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_catalogue', sa.Column('ид_объект', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_channel_catalogue_ид_объект'), 'channel_catalogue', ['ид_объект'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_catalogue_ид_объект'), table_name='channel_catalogue')
    op.drop_column('channel_catalogue', 'ид_объект')
    # ### end Alembic commands ###
